### ISSUE TITLE
Cannot read property 'statusUrl' of undefined - Please Help 

### ISSUE THREAD

**Issue by sushenmathur** [Supereg/homebridge-http-speaker#10]
Getting the below error, 
`TypeError: Cannot read property 'statusUrl' of undefined
    at new HTTP_SPEAKER (/homebridge/node_modules/homebridge-http-speaker/index.js:21:43)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

the GET API call statusURL is returning a 0 & 1
![image](https://user-images.githubusercontent.com/21048866/63828518-21311980-c9aa-11e9-99d6-9d6fe590c5e7.png)

here is my config.json 

`"accessories": [
        {
            "accessory": "HTTP-SPEAKER",
            "name": "Soundbar",
            
            "mute": {
                "onUrl": "http://localhost:3001/muteon",
                "offUrl": "http://localhost:3001/muteoff",

                "statusUrl": "http://localhost:3001/mutestatus"
            },
            
            "power": {
                "statusUrl": "http://localhost:3001/powerstatus",
                "onUrl": "http://localhost:3001/turnon",
                "offUrl": "http://localhost:3001/turnoff"
            }
        }
    ]`

**Comment by Supereg** [comment]
The plugin currently also expects the ‘volume‘ object to be configured as seen in the example configuration of the README.

**Comment by sushenmathur** [comment]
It said volume is fully optional hence why i did not configure, will try with volume

**Comment by sushenmathur** [comment]
Manage to get it added in home app but the accessory says not supported
![image](https://user-images.githubusercontent.com/21048866/63915651-ec8c9300-ca79-11e9-964d-3a49c58039cf.png)

**Comment by Supereg** [comment]
Please read the compatibility notice in the README file
